# GitHub Actions 自动化工作流
name: Sora 质量检查

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: 代码格式检查
      run: |
        black --check main.py services/

    - name: 代码质量检查
      run: |
        pylint main.py services/ --exit-zero

    - name: 类型检查
      run: |
        mypy main.py --ignore-missing-imports

    - name: 运行测试
      run: |
        pytest tests/ -v --cov=main

    - name: 构建检查
      run: |
        python main.py --version || echo "构建检查完成"